<a href="https://colab.research.google.com/github/mkgreen/DataProcessingAssignment/blob/main/Pandas%26NumPy_Project_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1) Generate an array of zeroes using inbuilt NumPy function.

In [1]:
import numpy as np
np.zeros(5)

array([0., 0., 0., 0., 0.])

## 2) Run the given code and find the dot product of both arrays.

In [2]:
import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)

[[2 4 3 5]
 [3 9 3 6]
 [5 9 2 5]]
[[8 2 3]
 [3 2 7]
 [2 5 6]
 [5 4 4]]


In [3]:
a.dot(b)

array([[ 59,  47,  72],
       [ 87,  63, 114],
       [ 96,  58, 110]])

In [4]:
b.dot(a)

array([[ 37,  77,  36,  67],
       [ 47,  93,  29,  62],
       [ 49, 107,  33,  70],
       [ 42,  92,  35,  69]])

# 3) Read the csv file provided using pandas and display the first 5 entries 

In [5]:
import pandas as pd

data = pd.read_csv("/content/data.csv")
data.head()

OBJECTID                        UNIT_NAME DESCRIPTION   ACRES  SHAPE.AREA  \
0        21        Fort Stevenson State Park  State Park  586.48    0.000284   
1        22           Beaver Lake State Park  State Park  273.16    0.000129   
2        23  Fort Abraham Lincoln State Park  State Park  836.47    0.000399   
3        24           Fort Ransom State Park  State Park  933.78    0.000444   
4        25        Grahams Island State Park  State Park  959.33    0.000469   

   SHAPE.LEN  
0   0.135641  
1   0.080067  
2   0.119868  
3   0.128733  
4   0.125546

# 4) Describe the data with all features.

In [26]:
data.info()
print("*"*62)
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   OBJECTID     25 non-null     int64  
 1   UNIT_NAME    25 non-null     object 
 2   DESCRIPTION  25 non-null     object 
 3   ACRES        25 non-null     float64
 4   SHAPE.AREA   25 non-null     float64
 5   SHAPE.LEN    25 non-null     float64
 6   NEW_FEATURE  25 non-null     float64
dtypes: float64(4), int64(1), object(2)
memory usage: 1.5+ KB
**************************************************************


OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN  NEW_FEATURE
count  25.000000    25.000000   25.000000  25.000000    25.000000
mean   33.000000   724.134400    0.000352   0.109863     0.564988
std     7.359801  1275.490247    0.000617   0.089073     0.275480
min    21.000000    11.400000    0.000005   0.009396     0.179111
25%    27.000000    72.300000    0.000034   0.033885     0.264813
50%    33.000000   524.810000    0.000256   0.087192     0.558499
75%    39.000000   836.470000    0.000399   0.145220     0.794306
max    45.000000  6492.930000    0.003136   0.338800     0.975992

# 5) Find the total count of missing values for each feature.

In [23]:
print("Total missing value counts for each feature:")
print("="*44)
print("")
print(data.isnull().sum())


missing_value_count = data.isnull().sum().sum()
if missing_value_count == 0:
    print("")
    print("There are no missing values in this dataset.")
else:
  print("")
  print(f"There are {missing_value_count} missing values in this dataset.")


Total missing value counts for each feature:

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
NEW_FEATURE    0
dtype: int64

There are no missing values in this dataset.


## 6) Display all the unique values from the 'DESCRIPTION' column


In [9]:
data.DESCRIPTION.unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

In [10]:
data.value_counts('DESCRIPTION')

DESCRIPTION
State Park               13
State Recreation Area     7
State Natural Area        2
State Nature Preserve     2
Interpretive Center       1
dtype: int64

# 7) Create a grouped table using 'DESCRIPTION' as the grouping columns with the means of all the other columns.

In [11]:
data.groupby(['DESCRIPTION']).mean()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

# 8) Generate a random sample of 10 rows from the data



In [12]:
data.sample(10)

OBJECTID                              UNIT_NAME            DESCRIPTION  \
12        35   Butte St. Paul State Recreation Area  State Recreation Area   
20        41      Missouri River State Natural Area     State Natural Area   
9         30      Fort Mandan State Recreation Area  State Recreation Area   
18        39        Gunlogson State Nature Preserve  State Nature Preserve   
8         29    Lewis and Clark Interpretive Center    Interpretive Center   
22        44  Turtle Mountain State Recreation Area  State Recreation Area   
0         21              Fort Stevenson State Park             State Park   
3         24                 Fort Ransom State Park             State Park   
7         28             Lewis and Clark State Park             State Park   
1         22                 Beaver Lake State Park             State Park   

     ACRES  SHAPE.AREA  SHAPE.LEN  
12   51.23    0.000025   0.022095  
20  174.39    0.000083   0.087192  
9    11.40    0.000005   0.009396  
18   95.89    0.000048   0.040465  
8    14.71    0.000007   0.016774  
22  695.04    0.000345   0.086487  
0   586.48    0.000284   0.135641  
3   933.78    0.000444   0.128733  
7   524.81    0.000256   0.130420  
1   273.16    0.000129   0.080067

# 9) Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using NumPy

In [13]:
import numpy as np
from numpy import random
random_data = np.random.uniform(0,1, size=25)
random_data

array([0.21322033, 0.64404658, 0.31522509, 0.20440762, 0.70195045,
       0.6980049 , 0.81792651, 0.90194823, 0.55595679, 0.26481269,
       0.86364255, 0.74963698, 0.20445521, 0.55849906, 0.25537355,
       0.51017066, 0.97599186, 0.76138114, 0.79430578, 0.51398064,
       0.93899993, 0.34344806, 0.23149487, 0.17911122, 0.92670674])

In [14]:
data['NEW_FEATURE']= list(random_data)
data.head()

OBJECTID                        UNIT_NAME DESCRIPTION   ACRES  SHAPE.AREA  \
0        21        Fort Stevenson State Park  State Park  586.48    0.000284   
1        22           Beaver Lake State Park  State Park  273.16    0.000129   
2        23  Fort Abraham Lincoln State Park  State Park  836.47    0.000399   
3        24           Fort Ransom State Park  State Park  933.78    0.000444   
4        25        Grahams Island State Park  State Park  959.33    0.000469   

   SHAPE.LEN  NEW_FEATURE  
0   0.135641     0.213220  
1   0.080067     0.644047  
2   0.119868     0.315225  
3   0.128733     0.204408  
4   0.125546     0.701950

# 10) Replace zero value of column 'OBJECTID' with mean value permanently.

In [16]:
data['OBJECTID'] = data['OBJECTID'].fillna(data['OBJECTID'].mean())